### PR TITLE
added more api functions

### PR DESCRIPTION
**Pull request by aembke**
Rework of this PR

https://github.com/7eggs/node-tesseract/pull/1

### CODE REVIEW

**Comment by aembke** [comment]
Also, regarding your nan comment, I've never used it, but upon a first look it looks pretty nifty. I wasn't aware of any incompatibilities but it couldn't hurt to be proactive about it.

**Comment by estliberitas** [comment]
@aembke okay, I'll start refactoring this weekend

**Comment by estliberitas** [comment]
@aembke I'll review and publish your changes tmrw, is this okay? Gonna rest now.

**Comment by aembke** [comment]
Yeah of course no problem. No rush on any of this.

**Comment by estliberitas** [comment]
LGTM

**Comment by estliberitas** [comment]
`v0.0.2` is out

**Pull request merged**
